
#### Doelgedragingen

In deze ronde zijn drie gedragingen uitgevraagd: zelf grenzen aangeven als iemand die overschrijdt, een vriend(in) aanspreken als die iemands grenzen lijkt te overschrijden, en het kenbaar maken bij vriend(inn)en als eigen grenzen zijn overschreden.

(De aanbevelingen worden pas toegevoegd als deze zijn geformuleerd.)

##### Het aangeven van grenzen

###### Sub-determinanten (opvattingen) binnen attitude

###### Sub-determinanten (opvattingen) binnen waargenomen norm

###### Sub-determinanten (opvattingen) binnen waargenomen gedragscontrole


##### Vrienden aanspreken op grensovertreding

###### Sub-determinanten (opvattingen) binnen attitude

###### Sub-determinanten (opvattingen) binnen waargenomen norm

###### Sub-determinanten (opvattingen) binnen waargenomen gedragscontrole


##### Ervaren grensovertreding met vrienden bespreken

###### Sub-determinanten (opvattingen) binnen attitude

###### Sub-determinanten (opvattingen) binnen waargenomen norm

###### Sub-determinanten (opvattingen) binnen waargenomen gedragscontrole

